"""empty message

Revision ID: 28549dbb57d0
Revises: 2f9ccc3bb8ee
Create Date: 2020-09-21 20:51:22.451829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28549dbb57d0'
down_revision = '2f9ccc3bb8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artistgenre')
    op.drop_table('venuegenre')
    op.drop_table('genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venuegenre',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='venuegenre_genre_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name='venuegenre_venue_id_fkey', ondelete='CASCADE')
    )
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('genre_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='genre_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('artistgenre',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='artistgenre_artist_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='artistgenre_genre_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
