"""empty message

Revision ID: d81af075e397
Revises: c10bb7434a48
Create Date: 2020-09-19 08:42:25.451467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81af075e397'
down_revision = 'c10bb7434a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###
