"""empty message

Revision ID: e0d04e7e5677
Revises: d5d13980c58f
Create Date: 2020-09-19 16:07:10.956367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d04e7e5677'
down_revision = 'd5d13980c58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'artistgenre', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'artistgenre', 'genre', ['genre_id'], ['id'])
    op.drop_column('artistgenre', 'id')
    op.create_foreign_key(None, 'venuegenre', 'genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'venuegenre', 'venue', ['venue_id'], ['id'])
    op.drop_column('venuegenre', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venuegenre', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venuegenre', type_='foreignkey')
    op.drop_constraint(None, 'venuegenre', type_='foreignkey')
    op.add_column('artistgenre', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'artistgenre', type_='foreignkey')
    op.drop_constraint(None, 'artistgenre', type_='foreignkey')
    # ### end Alembic commands ###
